spring:
  application:
    name: demo
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: ex
    password: ex

mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
      map-underscore-to-camel-case: true